sonar.projectKey=com.chavaillaz:jaxrs-logging
sonar.projectName=JAX-RS Requests Logging
sonar.organization=chavaillaz
sonar.language=java
sonar.sources=src/main/java/
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=https://sonarcloud.io
