name: System tests
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up
        uses: ./.github/actions/setup

      - name: Build project
        run: mvn -B -Pcoverage verify
