name: System tests
on: [ push, pull_request_target ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Set up
        uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn -B -Pcoverage verify

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --include-provided-dependencies=false

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif