name: System tests
on: [ push, pull_request_target ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Set up
        uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn -B -Pcoverage verify